[package]
name = "kbf-front"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
bytes.workspace = true
futures.workspace = true
kbf-meta.workspace = true
kbf-objstore.workspace = true
kbf-proto.workspace = true
kbf-segments.workspace = true
kbf-types.workspace = true
prost.workspace = true
thiserror.workspace = true
tonic.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }

[lints]
workspace = true
